# Generated by Django 5.2.10 on 2026-01-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100, verbose_name='Nome do Corredor')),
                ('quantidade_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='KM Percorrido')),
                ('foto_comprovante', models.ImageField(upload_to='comprovantes/', verbose_name='Foto do Comprovante')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Mês (Número)')),
                ('ano', models.IntegerField(default=2026)),
                ('objetivo_km', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Meta Total (KM)')),
            ],
        ),
    ]
